# This is a basic workflow to help you get started with Actions

name: Test API Controllers

# Controls when the workflow will run
env:
  MONGO_TEST_URI : 'mongodb://localhost:27017/test-db'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: 
      - '**.js'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  TEST_API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
      - name: Installing NPM Packages
        working-directory: api
        run: npm install
      - name: Running Tests
        working-directory: api
        run: npm test

