# This is a basic workflow to help you get started with Actions

name: Test API Controllers

# Controls when the workflow will run
env:
  MONGO_TEST_URI : 'mongodb://localhost:27017/test-db'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
      - name: Installing NPM Packages
        working-directory: api
        run: npm install
      - name: Running Tests
        working-directory: api
        run: npm test
